name: "gotestsum CI reactions"

on:
  check_run:
    types: [completed]

jobs:
  ci-react:
    if: github.event.check_run.app.slug == 'circleci-checks'
    name: Perform actions based on CI artifacts
    runs-on: ubuntu-latest
    env:
      CIRCLECI_PROJECT_SLUG: "gh/${{ github.repository }}"
      CHECKRUN_EXTERNAL_ID: "${{ github.event.check_run.external_id }}"
      EVENT: ${{ toJson(github.event) }}
    steps:
    - name: Perform actions 
      run: |
        echo ok

