name: "Test when events fire"

on:
  status:
  check_suite:
    types: [completed]

jobs:
  print:
    name: Print event context
    runs-on: ubuntu-latest
    env:
      EVENT: ${{ toJson(github.event) }}
      URL: ${{ github.event.check_suite.check_runs_url }}
    steps:
    - name: debug
      run: echo $EVENT
    - name: find artifacts
      run: |
        workflow_url=$(curl -sSL "$URL" | jq -r '.[].details_url')
        echo "$workflow_url"
        curl -sSL "$workflow_url"

