name: "gotestsum CI reactions"

on:
  check_run:
    types: [completed]

jobs:
  ci-react:
    if: github.event.check_run.app.slug == 'circleci-checks'
    name: Perform actions based on CI artifacts
    runs-on: ubuntu-latest

    env:
      CIRCLECI_PROJECT_SLUG: "gh/${{ github.repository }}"
      CIRCLECI_WORKFLOW: "${{ github.event.check_run.external_id }}"
      CIRCLECI_TOKEN: "${{ secrets.CIRCLECI_TOKEN }}"

    steps:
    - name: Install gotestsum
      run: |
        go mod init gotools
        go get gotest.tools/gotestsum@48af2b256e52f4ecee4015972221abd6b801e52f
    - name: Perform actions
      run: |
        export PATH=$PATH:~/go/bin
        gotestsum tool ci-action

